
export const data = [
    {
    img:'./img/card 1.svg',
    name: 'Постоянное наличие',
    text: 'Прямая работа с производителем обеспечивает постоянное наличие всех видом металлопроката'
    },
    {
    img:'./img/card 2.svg',
    name: 'Собственный автопарк',
    text: 'Автомобили грузоподъемностью от 1.5 до 20 тонн. Всегда быстрая доставка.'
    },
    {
    img:'./img/card 3.svg',
    name: 'Объемы поставок',
    text: 'Собственная служба доставки, гаранатирует вам поставку материалов на объект в кратчайшие сроки.'
    },
    {
    img:'./img/card 4.svg',
    name: 'Справедливая цена',
    text: 'Собственные ресурсы и транспорт позволяют снижать стоимость.'
    },
    {
    img:'./img/card 5.svg',
    name: 'Обработка заявки < 30 минут',
    text: 'Отдел продаж, насчитывающий более 80 сотрудников, не оставит вашу заявку без внимания.'
    },
    {
    img:'./img/card 6.png',
    name: 'Погрузка без очередей',
    text: 'Развитая складская логистика позволяет отгружать продукцию всегда без очередей.'
    },
];

export const metal = [
    {
    img1:'./img/metall1.png',
    img2:'./img/413 p.svg',
    name1: 'Металлочерепица <br> Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    color: "Цвет",
    input: "RAL 7004",
    valie1:"RAL 7005",
    valie2:"RAL 7006",
    valie3:"RAL 7007",
    width: "Толщина",
    input1:"0,4",
    walie1:"0,5",
    walie2:"0,6",
    walie3:"0,7",
    face: 'Поверхность',
    input2:"выбрать",
    vallie1:"не выбрать",
    vallie2:"думать",
    vallie3:"не думать",
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',

},
{
        img1:'./img/m2.png',
        img2:'./img/413 p.svg',
        name1: 'Металлочерепица <br> Kamea',
        brand: "Бренд",
        height: "Высота волны, мм",
        metre: "Высота ступеньки, мм",
        grand: "Grande Line",
        number: "23.5",
        num: "20",
        color: "Цвет",
        input: "RAL 7004",
        valie1:"RAL 7005",
        valie2:"RAL 7006",
        valie3:"RAL 7007",
        width: "Толщина",
        input1:"0,4",
        walie1:"0,5",
        walie2:"0,6",
        walie3:"0,7",
        face: 'Поверхность',
        input2:"выбрать",
        vallie1:"не выбрать",
        vallie2:"думать",
        vallie3:"не думать",
        button: "Рассчитать стоимость",
        buttonn: 'Подробнее о товаре',
    
 },
{
        img1:'./img/m3.png',
        img2:'./img/413 p.svg',
        name1: 'Металлочерепица <br> Kredo',
        brand: "Бренд",
        height: "Высота волны, мм",
        metre: "Высота ступеньки, мм",
        grand: "Grande Line",
        number: "23.5",
        num: "20",
        color: "Цвет",
        input: "RAL 7004",
        valie1:"RAL 7005",
        valie2:"RAL 7006",
        valie3:"RAL 7007",
        width: "Толщина",
        input1:"0,4",
        walie1:"0,5",
        walie2:"0,6",
        walie3:"0,7",
        face: 'Поверхность',
        input2:"выбрать",
        vallie1:"не выбрать",
        vallie2:"думать",
        vallie3:"не думать",
        button: "Рассчитать стоимость",
        buttonn: 'Подробнее о товаре',
    
 },
 {
            img1:'./img/m4.png',
            img2:'./img/413 p.svg',
            name1: 'Металлочерепица <br> Kvinta Plus',
            brand: "Бренд",
            height: "Высота волны, мм",
            metre: "Высота ступеньки, мм",
            grand: "Grande Line",
            number: "23.5",
            num: "20",
            color: "Цвет",
            input: "RAL 7004",
            valie1:"RAL 7005",
            valie2:"RAL 7006",
            valie3:"RAL 7007",
            width: "Толщина",
            input1:"0,4",
            walie1:"0,5",
            walie2:"0,6",
            walie3:"0,7",
            face: 'Поверхность',
            input2:"выбрать",
            vallie1:"не выбрать",
            vallie2:"думать",
            vallie3:"не думать",
            button: "Рассчитать стоимость",
            buttonn: 'Подробнее о товаре',
        
 },
 {
                img1:'./img/m5.png',
                img2:'./img/413 p.svg',
                name1: 'Металлочерепица <br> Kvinta plus 3D',
                brand: "Бренд",
                height: "Высота волны, мм",
                metre: "Высота ступеньки, мм",
                grand: "Grande Line",
                number: "23.5",
                num: "20",
                color: "Цвет",
                input: "RAL 7004",
                valie1:"RAL 7005",
                valie2:"RAL 7006",
                valie3:"RAL 7007",
                width: "Толщина",
                input1:"0,4",
                walie1:"0,5",
                walie2:"0,6",
                walie3:"0,7",
                face: 'Поверхность',
                input2:"выбрать",
                vallie1:"не выбрать",
                vallie2:"думать",
                vallie3:"не думать",
                button: "Рассчитать стоимость",
                buttonn: 'Подробнее о товаре',
            
 },
 {
                    img1:'./img/m6.png',
                    img2:'./img/413 p.svg',
                    name1: 'Металлочерепица <br> Kvinta Uno',
                    brand: "Бренд",
                    height: "Высота волны, мм",
                    metre: "Высота ступеньки, мм",
                    grand: "Grande Line",
                    number: "23.5",
                    num: "20",
                    color: "Цвет",
                    input: "RAL 7004",
                    valie1:"RAL 7005",
                    valie2:"RAL 7006",
                    valie3:"RAL 7007",
                    width: "Толщина",
                    input1:"0,4",
                    walie1:"0,5",
                    walie2:"0,6",
                    walie3:"0,7",
                    face: 'Поверхность',
                    input2:"выбрать",
                    vallie1:"не выбрать",
                    vallie2:"думать",
                    vallie3:"не думать",
                    button: "Рассчитать стоимость",
                    buttonn: 'Подробнее о товаре',
                
},
 {
                        img1:'./img/m7.png',
                        img2:'./img/413 p.svg',
                        name1: 'Металлочерепица <br> Modern',
                        brand: "Бренд",
                        height: "Высота волны, мм",
                        metre: "Высота ступеньки, мм",
                        grand: "Grande Line",
                        number: "23.5",
                        num: "20",
                        color: "Цвет",
                        input: "RAL 7004",
                        valie1:"RAL 7005",
                        valie2:"RAL 7006",
                        valie3:"RAL 7007",
                        width: "Толщина",
                        input1:"0,4",
                        walie1:"0,5",
                        walie2:"0,6",
                        walie3:"0,7",
                        face: 'Поверхность',
                        input2:"выбрать",
                        vallie1:"не выбрать",
                        vallie2:"думать",
                        vallie3:"не думать",
                        button: "Рассчитать стоимость",
                        buttonn: 'Подробнее о товаре',
                    
 },
 {
                            img1:'./img/m8.png',
                            img2:'./img/413 p.svg',
                            name1: 'Металлочерепица <br> Quadro Profi',
                            brand: "Бренд",
                            height: "Высота волны, мм",
                            metre: "Высота ступеньки, мм",
                            grand: "Grande Line",
                            number: "23.5",
                            num: "20",
                            color: "Цвет",
                            input: "RAL 7004",
                            valie1:"RAL 7005",
                            valie2:"RAL 7006",
                            valie3:"RAL 7007",
                            width: "Толщина",
                            input1:"0,4",
                            walie1:"0,5",
                            walie2:"0,6",
                            walie3:"0,7",
                            face: 'Поверхность',
                            input2:"выбрать",
                            vallie1:"не выбрать",
                            vallie2:"думать",
                            vallie3:"не думать",
                            button: "Рассчитать стоимость",
                            buttonn: 'Подробнее о товаре',
                        
 },
                                                                                                           
];

 export const prof = [
    {
        imgg:'./img/proff.png',
        imgg1:'./img/286.svg',
        name2: 'Профнастил C8',
        brand2: "Бренд",
        height2: "Ширина общая, мм",
        metre2: "Ширина полезная, мм",
        grand2: "Grande Line",
        number2: "1200",
        num2: "1160",
        colorr: "Цвет",
        inputt: "Оцинкованный",
        valie11:"Оцинкованный.2",
        valie22:"Оцинкованный.3",
        valie33:"Оцинкованный.4",
        widthh: "Толщина",
        input11:"0,35",
        walie11:"0,45",
        walie22:"0,55",
        walie33:"0,65",
        facee: 'Поверхность',
        input22:"выбрать",
        vallie11:"не выбрать",
        vallie22:"думать",
        vallie33:"не думать",
        buttonn: "Рассчитать стоимость",
        buttonnn: 'Подробнее о товаре',
    
    },
    {
        imgg:'./img/p2.png',
        imgg1:'./img/286.svg',
        name2: 'Профнастил C10',
        brand2: "Бренд",
        height2: "Ширина общая, мм",
        metre2: "Ширина полезная, мм",
        grand2: "Grande Line",
        number2: "1200",
        num2: "1160",
        colorr: "Цвет",
        inputt: "Оцинкованный",
        valie11:"Оцинкованный.2",
        valie22:"Оцинкованный.3",
        valie33:"Оцинкованный.4",
        widthh: "Толщина",
        input11:"0,35",
        walie11:"0,45",
        walie22:"0,55",
        walie33:"0,65",
        facee: 'Поверхность',
        input22:"выбрать",
        vallie11:"не выбрать",
        vallie22:"думать",
        vallie33:"не думать",
        buttonn: "Рассчитать стоимость",
        buttonnn: 'Подробнее о товаре',
    
    },
    {
        imgg:'./img/p3.png',
        imgg1:'./img/286.svg',
        name2: 'Профнастил C20',
        brand2: "Бренд",
        height2: "Ширина общая, мм",
        metre2: "Ширина полезная, мм",
        grand2: "Grande Line",
        number2: "1200",
        num2: "1160",
        colorr: "Цвет",
        inputt: "Оцинкованный",
        valie11:"Оцинкованный.2",
        valie22:"Оцинкованный.3",
        valie33:"Оцинкованный.4",
        widthh: "Толщина",
        input11:"0,35",
        walie11:"0,45",
        walie22:"0,55",
        walie33:"0,65",
        facee: 'Поверхность',
        input22:"выбрать",
        vallie11:"не выбрать",
        vallie22:"думать",
        vallie33:"не думать",
        buttonn: "Рассчитать стоимость",
        buttonnn: 'Подробнее о товаре',
    
    },
    {
        imgg:'./img/p4.png',
        imgg1:'./img/286.svg',
        name2: 'Профнастил C21',
        brand2: "Бренд",
        height2: "Ширина общая, мм",
        metre2: "Ширина полезная, мм",
        grand2: "Grande Line",
        number2: "1200",
        num2: "1160",
        colorr: "Цвет",
        inputt: "Оцинкованный",
        valie11:"Оцинкованный.2",
        valie22:"Оцинкованный.3",
        valie33:"Оцинкованный.4",
        widthh: "Толщина",
        input11:"0,35",
        walie11:"0,45",
        walie22:"0,55",
        walie33:"0,65",
        facee: 'Поверхность',
        input22:"выбрать",
        vallie11:"не выбрать",
        vallie22:"думать",
        vallie33:"не думать",
        buttonn: "Рассчитать стоимость",
        buttonnn: 'Подробнее о товаре',
    
    },
    {
        imgg:'./img/p5.png',
        imgg1:'./img/286.svg',
        name2: 'Профнастил HC35',
        brand2: "Бренд",
        height2: "Ширина общая, мм",
        metre2: "Ширина полезная, мм",
        grand2: "Grande Line",
        number2: "1200",
        num2: "1160",
        colorr: "Цвет",
        inputt: "Оцинкованный",
        valie11:"Оцинкованный.2",
        valie22:"Оцинкованный.3",
        valie33:"Оцинкованный.4",
        widthh: "Толщина",
        input11:"0,35",
        walie11:"0,45",
        walie22:"0,55",
        walie33:"0,65",
        facee: 'Поверхность',
        input22:"выбрать",
        vallie11:"не выбрать",
        vallie22:"думать",
        vallie33:"не думать",
        buttonn: "Рассчитать стоимость",
        buttonnn: 'Подробнее о товаре',
    
    },
    {
        imgg:'./img/p6.png',
        imgg1:'./img/286.svg',
        name2: 'Профнастил HC44',
        brand2: "Бренд",
        height2: "Ширина общая, мм",
        metre2: "Ширина полезная, мм",
        grand2: "Grande Line",
        number2: "1200",
        num2: "1160",
        colorr: "Цвет",
        inputt: "Оцинкованный",
        valie11:"Оцинкованный.2",
        valie22:"Оцинкованный.3",
        valie33:"Оцинкованный.4",
        widthh: "Толщина",
        input11:"0,35",
        walie11:"0,45",
        walie22:"0,55",
        walie33:"0,65",
        facee: 'Поверхность',
        input22:"выбрать",
        vallie11:"не выбрать",
        vallie22:"думать",
        vallie33:"не думать",
        buttonn: "Рассчитать стоимость",
        buttonnn: 'Подробнее о товаре',
    
    },
    {
        imgg:'./img/p7.png',
        imgg1:'./img/286.svg',
        name2: 'Профнастил H60',
        brand2: "Бренд",
        height2: "Ширина общая, мм",
        metre2: "Ширина полезная, мм",
        grand2: "Grande Line",
        number2: "1200",
        num2: "1160",
        colorr: "Цвет",
        inputt: "Оцинкованный",
        valie11:"Оцинкованный.2",
        valie22:"Оцинкованный.3",
        valie33:"Оцинкованный.4",
        widthh: "Толщина",
        input11:"0,35",
        walie11:"0,45",
        walie22:"0,55",
        walie33:"0,65",
        facee: 'Поверхность',
        input22:"выбрать",
        vallie11:"не выбрать",
        vallie22:"думать",
        vallie33:"не думать",
        buttonn: "Рассчитать стоимость",
        buttonnn: 'Подробнее о товаре',
    
    },  
      {
        imgg:'./img/p8.png',
        imgg1:'./img/286.svg',
        name2: 'Профнастил H75',
        brand2: "Бренд",
        height2: "Ширина общая, мм",
        metre2: "Ширина полезная, мм",
        grand2: "Grande Line",
        number2: "1200",
        num2: "1160",
        colorr: "Цвет",
        inputt: "Оцинкованный",
        valie11:"Оцинкованный.2",
        valie22:"Оцинкованный.3",
        valie33:"Оцинкованный.4",
        widthh: "Толщина",
        input11:"0,35",
        walie11:"0,45",
        walie22:"0,55",
        walie33:"0,65",
        facee: 'Поверхность',
        input22:"выбрать",
        vallie11:"не выбрать",
        vallie22:"думать",
        vallie33:"не думать",
        buttonn: "Рассчитать стоимость",
        buttonnn: 'Подробнее о товаре',
    
    },
];

 export const krov = [
    {
        img9:'./img/Product picture.png',
        imgg9:'./img/665.svg',
        name9: 'Кликфальц',
        brand9: "Бренд",
        height9: "Максимальная длина, м",
        metre9: "Минимальная длина, м",
        grand9: "Grande Line",
        number9: "9",
        num9: "1160",
        color9: "Цвет",
        input19: "Satin с пленкой на краях RAL",
        valie19:"Satin с пленкой на краях VAR",
        valie29:"Satin с пленкой на краях RES",
        valie39:"Satin с пленкой на краях VAS",
        width9: "Толщина",
        input29:"0,5",
        walie19:"0,6",
        walie29:"0,7",
        walie39:"0,8",
        face9: 'Поверхность',
        input39:"Глнянцевая",
        valliee9:"Глнянцевая 1",
        valliee19:"Глнянцевая 2",
        valliee29:"Глнянцевая 3",
        button9: "Рассчитать стоимость",
        button19: 'Подробнее о товаре',
    
    },
    {
        img9:'./img/f2.png',
        imgg9:'./img/665.svg',
        name9: 'Кликфальц Line',
        brand9: "Бренд",
        height9: "Максимальная длина, м",
        metre9: "Минимальная длина, м",
        grand9: "Grande Line",
        number9: "9",
        num9: "1160",
        color9: "Цвет",
        input19: "Satin с пленкой на краях RAL",
        valie19:"Satin с пленкой на краях VAR",
        valie29:"Satin с пленкой на краях RES",
        valie39:"Satin с пленкой на краях VAS",
        width9: "Толщина",
        input29:"0,5",
        walie19:"0,6",
        walie29:"0,7",
        walie39:"0,8",
        face9: 'Поверхность',
        input39:"Глнянцевая",
        valliee9:"Глнянцевая 1",
        valliee19:"Глнянцевая 2",
        valliee29:"Глнянцевая 3",
        button9: "Рассчитать стоимость",
        button19: 'Подробнее о товаре',
    
    },
    {
        img9:'./img/f3.png',
        imgg9:'./img/665.svg',
        name9: 'Кликфальц mini',
        brand9: "Бренд",
        height9: "Максимальная длина, м",
        metre9: "Минимальная длина, м",
        grand9: "Grande Line",
        number9: "9",
        num9: "1160",
        color9: "Цвет",
        input19: "Satin с пленкой на краях RAL",
        valie19:"Satin с пленкой на краях VAR",
        valie29:"Satin с пленкой на краях RES",
        valie39:"Satin с пленкой на краях VAS",
        width9: "Толщина",
        input29:"0,5",
        walie19:"0,6",
        walie29:"0,7",
        walie39:"0,8",
        face9: 'Поверхность',
        input39:"Глнянцевая",
        valliee9:"Глнянцевая 1",
        valliee19:"Глнянцевая 2",
        valliee29:"Глнянцевая 3",
        button9: "Рассчитать стоимость",
        button19: 'Подробнее о товаре',
    
    },
    {
        img9:'./img/f4.png',
        imgg9:'./img/665.svg',
        name9: 'Кликфальц Pro',
        brand9: "Бренд",
        height9: "Максимальная длина, м",
        metre9: "Минимальная длина, м",
        grand9: "Grande Line",
        number9: "9",
        num9: "1160",
        color9: "Цвет",
        input19: "Satin с пленкой на краях RAL",
        valie19:"Satin с пленкой на краях VAR",
        valie29:"Satin с пленкой на краях RES",
        valie39:"Satin с пленкой на краях VAS",
        width9: "Толщина",
        input29:"0,5",
        walie19:"0,6",
        walie29:"0,7",
        walie39:"0,8",
        face9: 'Поверхность',
        input39:"Глнянцевая",
        valliee9:"Глнянцевая 1",
        valliee19:"Глнянцевая 2",
        valliee29:"Глнянцевая 3",
        button9: "Рассчитать стоимость",
        button19: 'Подробнее о товаре',
    
    },
    {
        img9:'./img/f5.png',
        imgg9:'./img/665.svg',
        name9: 'Кликфальц Pro Golf',
        brand9: "Бренд",
        height9: "Максимальная длина, м",
        metre9: "Минимальная длина, м",
        grand9: "Grande Line",
        number9: "9",
        num9: "1160",
        color9: "Цвет",
        input19: "Satin с пленкой на краях RAL",
        valie19:"Satin с пленкой на краях VAR",
        valie29:"Satin с пленкой на краях RES",
        valie39:"Satin с пленкой на краях VAS",
        width9: "Толщина",
        input29:"0,5",
        walie19:"0,6",
        walie29:"0,7",
        walie39:"0,8",
        face9: 'Поверхность',
        input39:"Глнянцевая",
        valliee9:"Глнянцевая 1",
        valliee19:"Глнянцевая 2",
        valliee29:"Глнянцевая 3",
        button9: "Рассчитать стоимость",
        button19: 'Подробнее о товаре',
    
    },
    {
        img9:'./img/f6.png',
        imgg9:'./img/665.svg',
        name9: 'Кликфальц Pro line',
        brand9: "Бренд",
        height9: "Максимальная длина, м",
        metre9: "Минимальная длина, м",
        grand9: "Grande Line",
        number9: "9",
        num9: "1160",
        color9: "Цвет",
        input19: "Satin с пленкой на краях RAL",
        valie19:"Satin с пленкой на краях VAR",
        valie29:"Satin с пленкой на краях RES",
        valie39:"Satin с пленкой на краях VAS",
        width9: "Толщина",
        input29:"0,5",
        walie19:"0,6",
        walie29:"0,7",
        walie39:"0,8",
        face9: 'Поверхность',
        input39:"Глнянцевая",
        valliee9:"Глнянцевая 1",
        valliee19:"Глнянцевая 2",
        valliee29:"Глнянцевая 3",
        button9: "Рассчитать стоимость",
        button19: 'Подробнее о товаре',
    
    },
    {
        img9:'./img/f7.png',
        imgg9:'./img/665.svg',
        name9: 'Кликфальц двойной стоячий ',
        brand9: "Бренд",
        height9: "Максимальная длина, м",
        metre9: "Минимальная длина, м",
        grand9: "Grande Line",
        number9: "9",
        num9: "1160",
        color9: "Цвет",
        input19: "Satin с пленкой на краях RAL",
        valie19:"Satin с пленкой на краях VAR",
        valie29:"Satin с пленкой на краях RES",
        valie39:"Satin с пленкой на краях VAS",
        width9: "Толщина",
        input29:"0,5",
        walie19:"0,6",
        walie29:"0,7",
        walie39:"0,8",
        face9: 'Поверхность',
        input39:"Глнянцевая",
        valliee9:"Глнянцевая 1",
        valliee19:"Глнянцевая 2",
        valliee29:"Глнянцевая 3",
        button9: "Рассчитать стоимость",
        button19: 'Подробнее о товаре',
    
    },
    {
        img9:'./img/f8.png',
        imgg9:'./img/665.svg',
        name9: 'Фальц двойной Line',
        brand9: "Бренд",
        height9: "Максимальная длина, м",
        metre9: "Минимальная длина, м",
        grand9: "Grande Line",
        number9: "9",
        num9: "1160",
        color9: "Цвет",
        input19: "Satin с пленкой на краях RAL",
        valie19:"Satin с пленкой на краях VAR",
        valie29:"Satin с пленкой на краях RES",
        valie39:"Satin с пленкой на краях VAS",
        width9: "Толщина",
        input29:"0,5",
        walie19:"0,6",
        walie29:"0,7",
        walie39:"0,8",
        face9: 'Поверхность',
        input39:"Глнянцевая",
        valliee9:"Глнянцевая 1",
        valliee19:"Глнянцевая 2",
        valliee29:"Глнянцевая 3",
        button9: "Рассчитать стоимость",
        button19: 'Подробнее о товаре',
    
    },
];
